package router

const (
	// APILetters ...
	APILetters = "/letters"
	// APILettersLength ...
	APILettersLength = "/letters/length"
	// APIMoods ...
	APIMoods = "/moods"
	// APITags ...
	APITags = "/tags"
	// APIRegister ...
	APIRegister = "/register"
	// APILogin ...
	APILogin = "/login"
	// APIAvatar ...
	APIAvatar = "/accounts/:account/avatar"
)
